deployment:
  replicaCount: 1
  name: my-deployment
  image:
    app: nginx
    version: latest

service:
  name: my-service
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 32036

container1:
  enabled: true
