apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.deployment.image.app }}:{{ .Values.deployment.image.version}}"
        {{- if eq .Values.container1.enabled true -}}
        {{- include "container1" . | nindent 8 -}}

        {{/* 写法一： */}}
        {{- else if eq .Values.container1.enabled false -}}
        {{/* 写法二：
        {{- else -}}
        */}}
        {{- include "container2" . | nindent 8 -}}

        {{- end -}}
